services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realms/realms.json:/opt/keycloak/data/import/realms.json
      - ./target/keycloak-2factor-sms-mfa-1.0.jar:/opt/keycloak/providers/keycloak-2factor-sms-mfa.jar
